In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
data = pd.read_csv('https://raw.githubusercontent.com/kdemertzis/EKPA/main/Data/phishing_dataset.csv', delimiter=',')

In [2]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

,Domain,Have_IP,Have_At,URL_Length,URL_Depth,Redirection,https_Domain,TinyURL,Prefix/Suffix,DNS_Record,Web_Traffic,Domain_Age,Domain_End,iFrame,Mouse_Over,Right_Click,Web_Forwards,Label
0,u4131462.ct.sendgrid.net,0,0,1,2,0,0,0,0,0,1,0,1,0,0,1,0,1
1,123formbuilder.com,0,0,1,2,0,0,0,0,0,1,1,0,0,0,1,0,1
2,aljazeera.net,0,0,1,6,0,0,0,0,0,1,1,1,0,0,1,0,0
3,grrasawstraining.com,0,0,1,2,0,0,0,0,0,1,0,1,0,0,1,0,1
4,secure.runescape.com-ars.xyz,0,0,1,2,0,0,0,1,0,1,0,1,1,1,1,1,1


In [3]:
X = data.drop(['Domain', 'Label'], axis=1)

In [4]:
X.head()

,Have_IP,Have_At,URL_Length,URL_Depth,Redirection,https_Domain,TinyURL,Prefix/Suffix,DNS_Record,Web_Traffic,Domain_Age,Domain_End,iFrame,Mouse_Over,Right_Click,Web_Forwards
0,0,0,1,2,0,0,0,0,0,1,0,1,0,0,1,0
1,0,0,1,2,0,0,0,0,0,1,1,0,0,0,1,0
2,0,0,1,6,0,0,0,0,0,1,1,1,0,0,1,0
3,0,0,1,2,0,0,0,0,0,1,0,1,0,0,1,0
4,0,0,1,2,0,0,0,1,0,1,0,1,1,1,1,1


In [5]:
#y=np.ravel(data['Label'])
y=np.ravel(data['Label'])

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=43)

In [7]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
# Define classifiers
classifiers = [
    LogisticRegression(),
    SVC(),
    RandomForestClassifier(),
    MLPClassifier(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
]

In [9]:
# Evaluate and compare classifiers
results = {'Classifier': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1 Score': []}

for clf in classifiers:
    clf_name = clf.__class__.__name__

    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Display results
    print(f"\n{clf_name} Metrics:")
    print(f"Accuracy: {acc}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print("Confusion Matrix:")
    print(cm)

    # Store results for comparison
    results['Classifier'].append(clf_name)
    results['Accuracy'].append(acc)
    results['Precision'].append(precision)
    results['Recall'].append(recall)
    results['F1 Score'].append(f1)


LogisticRegression Metrics:
Accuracy: 0.8046666666666666
Precision: 0.8255326996506621
Recall: 0.8046666666666666
F1 Score: 0.8014642334972804
Confusion Matrix:
[[1398  103]
 [ 483 1016]]

SVC Metrics:
Accuracy: 0.8433333333333334
Precision: 0.875636805108588
Recall: 0.8433333333333334
F1 Score: 0.8398728230597304
Confusion Matrix:
[[1486   15]
 [ 455 1044]]

RandomForestClassifier Metrics:
Accuracy: 0.8663333333333333
Precision: 0.8721063810060494
Recall: 0.8663333333333333
F1 Score: 0.8658063326676914
Confusion Matrix:
[[1394  107]
 [ 294 1205]]


/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(



MLPClassifier Metrics:
Accuracy: 0.863
Precision: 0.8777969818563426
Recall: 0.863
F1 Score: 0.8616346584556214
Confusion Matrix:
[[1444   57]
 [ 354 1145]]

KNeighborsClassifier Metrics:
Accuracy: 0.8586666666666667
Precision: 0.8597897753155503
Recall: 0.8586666666666667
F1 Score: 0.8585531298090445
Confusion Matrix:
[[1331  170]
 [ 254 1245]]

DecisionTreeClassifier Metrics:
Accuracy: 0.865
Precision: 0.8712637458039124
Recall: 0.865
F1 Score: 0.8644212794928711
Confusion Matrix:
[[1396  105]
 [ 300 1199]]


In [10]:
# Display comparison results
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by='Accuracy', ascending=False)
print("\nComparison of Classifiers:")
print(results_df)


Comparison of Classifiers:
               Classifier  Accuracy  Precision    Recall  F1 Score
2  RandomForestClassifier  0.866333   0.872106  0.866333  0.865806
5  DecisionTreeClassifier  0.865000   0.871264  0.865000  0.864421
3           MLPClassifier  0.863000   0.877797  0.863000  0.861635
4    KNeighborsClassifier  0.858667   0.859790  0.858667  0.858553
1                     SVC  0.843333   0.875637  0.843333  0.839873
0      LogisticRegression  0.804667   0.825533  0.804667  0.801464
